### ISSUE TITLE
Broken demo config

### ISSUE THREAD

**Issue by c0c0n3** [IDSIA/adapquest#26]
When I try taking the "simple" survey in the demo, I get an internal server error. Stack trace below :-)

```
2023-04-03 10:44:46.099 INFO  ch.idsia.adaptive.backend.controller.SurveyController            Request test initialization with accessCode=AdapQuest-Example
2023-04-03 10:44:46.163 INFO  ch.idsia.adaptive.backend.services.SessionService                Registering new session with accessCode=AdapQuest-Example userAgent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 remoteAddress=127.0.0.1
2023-04-03 10:44:46.957 INFO  ch.idsia.adaptive.backend.controller.SurveyController            Request status for token=2b53921d-602d-42a8-93ac-d06200578455
2023-04-03 10:44:47.155 INFO  ch.idsia.adaptive.backend.controller.SurveyController            User with token=2b53921d-602d-42a8-93ac-d06200578455 request a new question
2023-04-03 10:44:47.252 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet] Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.IllegalArgumentException: no such vertex in graph: -1] with root cause
java.lang.IllegalArgumentException: no such vertex in graph: -1
	at org.jgrapht.graph.AbstractGraph.assertVertexExist(AbstractGraph.java:131)
	at org.jgrapht.graph.AbstractBaseGraph.outgoingEdgesOf(AbstractBaseGraph.java:484)
	at ch.idsia.crema.model.graphical.DAGModel.getChildren(DAGModel.java:257)
	at ch.idsia.crema.search.impl.DepthFirst.visit(DepthFirst.java:34)
	at ch.idsia.crema.search.impl.DepthFirst.visitAll(DepthFirst.java:25)
	at ch.idsia.crema.search.impl.DepthFirst.visit(DepthFirst.java:21)
	at ch.idsia.crema.preprocess.RemoveBarren.cutIndependent(RemoveBarren.java:131)
	at ch.idsia.crema.preprocess.RemoveBarren.executeInPlace(RemoveBarren.java:32)
	at ch.idsia.crema.inference.bp.LoopyBeliefPropagation.preprocess(LoopyBeliefPropagation.java:90)
	at ch.idsia.crema.inference.bp.LoopyBeliefPropagation.query(LoopyBeliefPropagation.java:185)
	at ch.idsia.crema.inference.bp.LoopyBeliefPropagation.query(LoopyBeliefPropagation.java:181)
	at ch.idsia.adaptive.backend.services.commons.inference.precise.InferenceLBP.query(InferenceLBP.java:21)
	at ch.idsia.adaptive.backend.services.commons.inference.precise.InferenceLBP.query(InferenceLBP.java:16)
	at ch.idsia.adaptive.backend.services.commons.agents.AgentPreciseAdaptive.nextQuestion(AgentPreciseAdaptive.java:152)
	at ch.idsia.adaptive.backend.services.commons.agents.AgentGeneric.next(AgentGeneric.java:219)
	at ch.idsia.adaptive.backend.services.SurveyManagerService.nextQuestion(SurveyManagerService.java:113)
	at ch.idsia.adaptive.backend.controller.SurveyController.nextQuestion(SurveyController.java:346)
	at ch.idsia.adaptive.backend.controller.SurveyController$$FastClassBySpringCGLIB$$544da7d.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at ch.idsia.adaptive.backend.controller.SurveyController$$EnhancerBySpringCGLIB$$8d27981f.nextQuestion(<generated>)
	at ch.idsia.adaptive.backend.controller.DemoController.survey(DemoController.java:162)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:502)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:596)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:186)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:492)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:768)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:389)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by cbonesana** [comment]
Fixed with version 1.6.3.
